/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dlink
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(
            ArrayList<Pedido> cadPedido,
            ArrayList<Pessoa> cadCliVend,
            ArrayList<Produto> cadProduto
    ) {
        initComponents();
        this.cadCliVend = cadCliVend;
        this.cadProduto = cadProduto;
        this.cadastro = cadPedido;
        this.cadItens = cadItens;
        
        modTblPedido = (DefaultTableModel)tblPedidos.getModel();
    }

    private void prepararPedidio(){
        txtNumPedido.setEnabled(false);
        btnProcurarPedido.setEnabled(false);
        txtData.setEnabled(true);
        rbtnAPrazo.setEnabled(true);
        rbtnAVista.setEnabled(true);
        txtCpfCliente.setEnabled(true);
        btnProcurarCliente.setEnabled(true);
        txtData.requestFocus();
    }
    
    private void preperarPedidoExistente(){ 
        txtCodProduto.setEnabled(true);
        
        txtCpfVendedor.setEnabled(true);
        btnProcurarVendedor.setEnabled(true);
        txtCodProduto.setEnabled(true);
        btnProcurarProduto.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnIncluir.setEnabled(false);
    }
    
    private void novo(){
        txtCodProduto.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        txtData.setEnabled(false);
        txtNomeCliente.setEnabled(false);
        txtNomeProduto.setEnabled(false);
        txtNomeVendedor.setEnabled(false);
        txtQtdItens.setEnabled(false);
        txtQtdVendida.setEnabled(false);
        txtValorTotalPedido.setEnabled(false);
        txtNumPedido.setEnabled(true);
        
        txtCodProduto.setText(null);
        txtCpfCliente.setText(null);
        txtCpfVendedor.setText(null);
        txtData.setText(null);
        txtNomeCliente.setText(null);
        txtNomeProduto.setText(null);
        txtNomeVendedor.setText(null);
        txtNumPedido.setText(null);
        txtQtdItens.setText(null);
        txtQtdVendida.setText(null);
        txtValorTotalPedido.setText(null);
        
        rbtnAPrazo.setSelected(false);
        rbtnAVista.setSelected(false);
        
        modTblPedido.setRowCount(0);
        
        btnAdd.setEnabled(false);
        btnRemover.setEnabled(false);
        btnProcurarCliente.setEnabled(false);
        btnProcurarPedido.setEnabled(true);
        btnProcurarProduto.setEnabled(false);
        btnProcurarVendedor.setEnabled(false);
        
        rbtnAPrazo.setEnabled(false);
        rbtnAVista.setEnabled(false);
        
        tblPedidos.setEnabled(false);
    }
    
    public void desabilitar(){
        txtCodProduto.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        txtData.setEnabled(false);
        txtNomeCliente.setEnabled(false);
        txtNomeProduto.setEnabled(false);
        txtNomeVendedor.setEnabled(false);
        txtQtdItens.setEnabled(false);
        txtQtdVendida.setEnabled(false);
        txtValorTotalPedido.setEnabled(false);
        txtNumPedido.setEnabled(false);
        tblPedidos.setEnabled(false);
        rbtnAPrazo.setEnabled(false);
        rbtnAVista.setEnabled(false);
        
        btnAdd.setEnabled(false);
        btnRemover.setEnabled(false);
        btnProcurarCliente.setEnabled(false);
        btnProcurarPedido.setEnabled(false);
        btnProcurarProduto.setEnabled(false);
        btnProcurarVendedor.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnProcurarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtnAVista = new javax.swing.JRadioButton();
        rbtnAPrazo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnProcurarCliente = new javax.swing.JButton();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnProcurarVendedor = new javax.swing.JButton();
        txtCpfVendedor = new javax.swing.JFormattedTextField();
        txtNomeVendedor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnProcurarProduto = new javax.swing.JButton();
        txtNomeProduto = new javax.swing.JTextField();
        txtCodProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdVendida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorTotalPedido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtdItens = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Número de Pedido");

        btnProcurarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnProcurarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        formaPagamento.add(rbtnAVista);
        rbtnAVista.setText("A Vista");
        rbtnAVista.setEnabled(false);

        formaPagamento.add(rbtnAPrazo);
        rbtnAPrazo.setText("A Prazo");
        rbtnAPrazo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rbtnAVista)
                .addGap(26, 26, 26)
                .addComponent(rbtnAPrazo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtnAPrazo)
                .addComponent(rbtnAVista))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel3.setText("CPF Cliente");

        btnProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnProcurarCliente.setEnabled(false);
        btnProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarClienteActionPerformed(evt);
            }
        });

        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.setEnabled(false);

        txtNomeCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeCliente)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        jLabel5.setText("CPF Vendedor");

        btnProcurarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnProcurarVendedor.setEnabled(false);
        btnProcurarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarVendedorActionPerformed(evt);
            }
        });

        try {
            txtCpfVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfVendedor.setEnabled(false);

        txtNomeVendedor.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcurarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeVendedor)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProcurarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel6.setText("Código do Produto");

        btnProcurarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnProcurarProduto.setEnabled(false);
        btnProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarProdutoActionPerformed(evt);
            }
        });

        txtNomeProduto.setEnabled(false);

        txtCodProduto.setEnabled(false);

        jLabel7.setText("Qtde Vendida");

        txtQtdVendida.setEnabled(false);
        txtQtdVendida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdVendidaFocusLost(evt);
            }
        });
        txtQtdVendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdVendidaActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor total do pedido");

        txtValorTotalPedido.setEditable(false);
        txtValorTotalPedido.setEnabled(false);

        jLabel9.setText("Quantidade de itens pedidos");

        txtQtdItens.setEditable(false);
        txtQtdItens.setEnabled(false);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnAdd.setText("Adicionar Item");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rem.png"))); // NOI18N
        btnRemover.setText("Remover Item");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vendida", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnProcurarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtQtdVendida, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtQtdVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProcurarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarPedidoActionPerformed
        if(txtNumPedido.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Código inválido", "Erro código", 2);
            txtNumPedido.requestFocus();
            return;
        }
        
        DecimalFormat formato = new DecimalFormat("#0.00");
        double total = 0;
        int quantidade = 0;
        
        int x;
        for (x = 0; x < cadastro.size(); x++) {
            if (cadastro.get(x).getNumero().equals(txtNumPedido.getText())) {
                break;
            }
        }
        
        if (x < cadastro.size()) {
            posPedido = x;
        } else {
            posPedido = -1;
        }
        
        prepararPedidio();
        
        if(posPedido >= 0){
            preperarPedidoExistente();
            desabilitar();
            txtData.setText(cadastro.get(posPedido).getDataEmissao());
            if(cadastro.get(posPedido).isFormaPagto()){
                rbtnAVista.setSelected(true);
            }else{
                rbtnAPrazo.setSelected(true);
            }
            txtCpfCliente.setText(cadastro.get(x).getCliente().getCpf());
            txtNomeCliente.setText(cadastro.get(x).getCliente().getNome());
            txtCpfVendedor.setText(cadastro.get(x).getVendedor().getCpf());
            txtNomeVendedor.setText(cadastro.get(x).getVendedor().getNome());
            
            for(int i = 0; i < cadastro.get(x).listarItens().size(); i++){
                String linha [] = {
                    String.valueOf(cadastro.get(x).listarItens().get(i).getProduto().getCodigo()),
                    cadastro.get(x).listarItens().get(i).getProduto().getDescricao(),
                    String.valueOf(formato.format(cadastro.get(x).listarItens().get(i).getProduto().getPreco())),
                    String.valueOf(cadastro.get(x).listarItens().get(i).getQtdeVendida()),
                    String.valueOf(formato.format(
                        cadastro.get(x).listarItens().get(i).getQtdeVendida()
                        *  cadastro.get(x).listarItens().get(i).getProduto().getPreco()
                    ))
                };
                total += cadastro.get(x).listarItens().get(i).getQtdeVendida()
                        *  cadastro.get(x).listarItens().get(i).getProduto().getPreco();
                
                quantidade += cadastro.get(x).listarItens().get(i).getQtdeVendida();
                modTblPedido.addRow(linha);
            }

            txtValorTotalPedido.setText(formato.format(total));
            txtQtdItens.setText(String.valueOf(quantidade));
        }
    }//GEN-LAST:event_btnProcurarPedidoActionPerformed

    private void btnProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarClienteActionPerformed
        for(posCliente = 0; posCliente < cadCliVend.size(); posCliente++) {
            if(cadCliVend.get(posCliente).getCpf().equals(txtCpfCliente.getText()))
            {
                txtNomeCliente.setText(cadCliVend.get(posCliente).getNome());
                txtCpfCliente.setEnabled(false);
                btnProcurarCliente.setEnabled(false);
                txtCpfVendedor.setEnabled(true);
                btnProcurarVendedor.setEnabled(true);
                txtCpfVendedor.requestFocus();
                break;
            }
                
            if(posCliente == cadCliVend.size() -1 ){
                JOptionPane.showMessageDialog(this, "Cliente não cadastrado", "Erro cliente", 2);
                txtCpfCliente.requestFocus();
                return;
            }       
        }
    }//GEN-LAST:event_btnProcurarClienteActionPerformed

    private void btnProcurarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarVendedorActionPerformed
        for(posVendedor = 0; posVendedor < cadCliVend.size(); posVendedor++) {
            if(cadCliVend.get(posVendedor).getCpf().equals(txtCpfVendedor.getText()))
            {
                txtCpfVendedor.setEnabled(false);
                btnProcurarVendedor.setEnabled(false);
                txtNomeVendedor.setText(cadCliVend.get(posVendedor).getNome());
                txtCodProduto.setEnabled(true);
                btnProcurarProduto.setEnabled(true);
                txtCodProduto.requestFocus();
                btnIncluir.setEnabled(true);
                break;
            }
                
             if(posVendedor == cadCliVend.size() -1 ){
                JOptionPane.showMessageDialog(this, "Vendedor não cadastrado", "Erro vendedor", 2);
                txtCpfVendedor.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_btnProcurarVendedorActionPerformed

    private void btnProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarProdutoActionPerformed
        for(posProduto = 0; posProduto < cadProduto.size(); posProduto++){
            if (cadProduto.get(posProduto).getCodigo().equals(txtCodProduto.getText())) {
                    btnAdd.setEnabled(true);
                    btnRemover.setEnabled(true);
                    txtNomeProduto.setText(cadProduto.get(posProduto).getDescricao());
                    txtQtdVendida.setEnabled(true);
                    txtQtdVendida.requestFocus();
                    break;
            }
            if(posProduto == cadProduto.size() -1 ){
                JOptionPane.showMessageDialog(this, "Produto não cadastrado", "Erro produto", 2);
                txtCodProduto.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_btnProcurarProdutoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtQtdVendida.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Quantidade inválida", "Erro quantidade", 2);
            txtQtdVendida.requestFocus();
            return;
        }   
            
        if(Integer.parseInt(txtQtdVendida.getText()) > cadProduto.get(posProduto).getQtdeEstoque()){
            JOptionPane.showMessageDialog(this, "Estoque insuficiente", "Erro quantidade", 2);
            txtQtdVendida.requestFocus();
            return;
        }
        
        if(Integer.parseInt(txtQtdVendida.getText()) > cadProduto.get(posProduto).getQtdeEstoque() - cadProduto.get(posProduto).getEstoqueMinimo()){
            JOptionPane.showMessageDialog(this, "Estoque insuficiente", "Erro quantidade", 2);
            txtQtdVendida.requestFocus();
            return;
        }
        
        double total = cadProduto.get(posProduto).getPreco() * Integer.parseInt(txtQtdVendida.getText());
        int quantidade = Integer.parseInt(txtQtdVendida.getText());
        
        if(total > ((Cliente)cadCliVend.get(posCliente)).getLimiteDisp()){
            JOptionPane.showMessageDialog(this, "Saldo insuficiente", "Erro adição de item", 2);
            txtQtdVendida.requestFocus();
            return;
        }
        
        ((Cliente)cadCliVend.get(posCliente)).setLimiteDisp(
            ((Cliente)cadCliVend.get(posCliente)).getLimiteDisp()
            - total
        );
        
        cadProduto.get(posProduto).setQtdeEstoque(
            cadProduto.get(posProduto).getQtdeEstoque()
            - Integer.parseInt(txtQtdVendida.getText())
        );
        
        String linha [] = {
            String.valueOf(cadProduto.get(posProduto).getCodigo()),
            String.valueOf(cadProduto.get(posProduto).getDescricao()),
            String.valueOf(cadProduto.get(posProduto).getPreco()),
            txtQtdVendida.getText(),
            String.valueOf(total)
        };
        
        modTblPedido.addRow(linha);
        totalPedido += total;
        qtdPedido += quantidade;
        txtValorTotalPedido.setText(String.valueOf(totalPedido));
        txtQtdItens.setText(String.valueOf(qtdPedido));
        
        ItemPedido item = new ItemPedido(
            modTblPedido.getRowCount() - 1,
            Integer.parseInt(txtQtdVendida.getText()),
            cadProduto.get(posProduto)                
        );
        
        
        
        cadItens.add(item);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int rowToBeRemoved = tblPedidos.getSelectedRow();
        int posProduto;
        int posItem;
        if(rowToBeRemoved < 0)
            JOptionPane.showMessageDialog(this, "Item não selecionado", "Erro de remoção", 2);
        else {
            for(posItem = 0; posItem < cadItens.size(); posItem++){
                if(cadItens.get(posItem).getSequencia() == rowToBeRemoved)
                    break;
            }
            
            double qtdVendida = cadItens.get(posItem).getQtdeVendida();
            
            double subtotal =
                cadItens.get(posItem).getProduto().getPreco()
                * cadItens.get(posItem).getQtdeVendida();
         
            cadItens.get(posItem).getProduto().setQtdeEstoque(
                cadItens.get(posItem).getProduto().getQtdeEstoque()
                + qtdVendida
            );
            
            ((Cliente)cadCliVend.get(posCliente)).setLimiteDisp(
                ((Cliente)cadCliVend.get(posCliente)).getLimiteDisp()
                + subtotal
            );
            
            modTblPedido.removeRow(rowToBeRemoved);
            
            totalPedido -= subtotal;
            qtdPedido -= qtdVendida;
            
            txtValorTotalPedido.setText(String.valueOf(subtotal));
            txtQtdItens.setText(String.valueOf(qtdPedido));
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        Pedido pedido = new Pedido(txtNumPedido.getText(), txtData.getText());
        
        pedido.setDataEmissao(txtData.getText());
        pedido.setDataPagto(String.valueOf(Calendar.DATE));
        pedido.setFormaPagto(formaPagamento.isSelected(rbtnAPrazo.getModel()));
        
        pedido.setCliente((Cliente)cadCliVend.get(posCliente));
        pedido.setVendedor((Vendedor)cadCliVend.get(posVendedor));
        pedido.setSituacao(true);
        pedido.setTotal(totalPedido);
        
        pedido.addItens(cadItens);
        //adicionar pedido e vendendor
        
        ((Vendedor)cadCliVend.get(posVendedor)).setSalarioBase(
            ((Vendedor)cadCliVend.get(posVendedor)).getTaxaComissao()
            * totalPedido
        );

        cadastro.add(pedido);
        
        novo();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

        try{
            format.setLenient(false);
            Date data = format.parse(txtData.getText());
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data errada", "Erro pedido", 2);
        }
        
        
    }//GEN-LAST:event_txtDataFocusLost

    private void txtQtdVendidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdVendidaFocusLost

    }//GEN-LAST:event_txtQtdVendidaFocusLost

    private void txtQtdVendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdVendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdVendidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnProcurarCliente;
    private javax.swing.JButton btnProcurarPedido;
    private javax.swing.JButton btnProcurarProduto;
    private javax.swing.JButton btnProcurarVendedor;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup formaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAPrazo;
    private javax.swing.JRadioButton rbtnAVista;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JFormattedTextField txtCpfVendedor;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeVendedor;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdItens;
    private javax.swing.JTextField txtQtdVendida;
    private javax.swing.JTextField txtValorTotalPedido;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pedido> cadastro;
    private ArrayList<Pessoa> cadCliVend;
    private ArrayList<Produto> cadProduto;
    private ArrayList<ItemPedido> cadItens = new ArrayList<ItemPedido>();
    private int posPedido;
    private DefaultTableModel modTblPedido;
    private int posCliente, posVendedor, posProduto;
    private double totalPedido = 0, qtdPedido = 0;
}
